[tool.poetry]
name = "artificial-non-intelligence"
version = "0.1.0"
description = ""
authors = ["Adrien Carpentier <moi@adriencarpentier.com>", "Phil Lin <philip.lin@gmail.com, "Dilnoza Mirdjalilova <dmirdjalilova@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
packgenlite = {git = "https://github.com/krokrob/packgenlite.git"}
peewee = "^3.14.4"
beautifulsoup4 = "^4.9.3"
typer = "^0.3.2"
requests = "^2.25.1"
selenium = "^3.141.0"
chromedriver-binary = "^91.0.4472"
gcsfs = "^2021.5.0"
google-cloud-storage = "^1.38.0"
mlflow = "^1.17.0"
s3fs = "^2021.5.0"
scikit-learn = "^0.24.2"
pandas = "^1.2.4"
pytest = "^6.2.4"
coverage = "^5.5"
memoized-property = "^1.0.3"
gunicorn = "^20.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
