[tool.poetry]
name = "artificial-non-intelligence"
version = "0.1.0"
description = ""
authors = ["Adrien Carpentier <moi@adriencarpentier.com>"]

[tool.poetry.dependencies]
python = "^3.9"
packgenlite = {git = "https://github.com/krokrob/packgenlite.git"}
peewee = "^3.14.4"
beautifulsoup4 = "^4.9.3"
typer = "^0.3.2"
requests = "^2.25.1"
selenium = "^3.141.0"
chromedriver-binary = "^91.0.4472"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
